services:
  backend:
    build:
      context: .
      target: backend
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/fitness_tracker
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_FLYWAY_USER=root
      - SPRING_FLYWAY_PASSWORD=password
    develop:
      watch:
        - path: ./src
          action: sync
          target: /usr/local/app/src
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - 8080:8080
    networks:
      - app-network
  mysql:
    image: mysql:8.0
    volumes:
      - fitness-tracker-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: fitness_tracker
    ports:
      - 3306:3306
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    networks:
      - app-network

volumes:
  fitness-tracker-data:

networks:
  app-network:
    driver: bridge